apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  namespace: alpha
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
        - name: wordpress
          image: wordpress
          env:
            - name: WORDPRESS_DB_HOST
              value: db
            - name: WORDPRESS_DB_USER
              value: exampleuser
            - name: WORDPRESS_DB_PASSWORD
              value: examplepass
            - name: WORDPRESS_DB_NAME
              value: exampledb
---
apiVersion: v1
kind: Service
metadata:
  name: wordpress
  namespace: alpha
spec:
  selector:
    app: wordpress
  ports:
    - port: 80
      targetPort: 80
