# Example 3
# Use yaml from different branch
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: example3
  namespace: alpha
spec:
  interval: 0m10s
  sourceRef:
    kind: GitRepository
    name: alpha-example3
    namespace: flux-system
  path: ./
  prune: true
  wait: true
  timeout: 5m0s
