# Example 1
# Yaml file directly in clusters/dev/namespaces/charlie
apiVersion: apps/v1
kind: Deployment
metadata:
  name: example7
  namespace: charlie
  labels:
    app: example7
spec:
  replicas: 1
  selector:
    matchLabels:
      app: example7
  template:
    metadata:
      labels:
        app: example7
    spec:
      containers:
        - name: example7
          image: nginx:latest
---
apiVersion: v1
kind: Service
metadata:
  name: example7
  namespace: charlie
spec:
  selector:
    app: example7
  ports:
    - port: 80
      targetPort: 80
