# example4 helm release from bitnami helm repository
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: example4
  namespace: alpha
spec:
  interval: 0m10s
  chart:
    spec:
      chart: nginx
      version: 15.1.4
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      interval: 0m10s
  values:
    fullnameOverride: example4
    service:
      type: ClusterIP
