apiVersion: apps/v1
kind: Deployment
metadata:
  name: example3
  namespace: alpha
  labels:
    app: example3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: example3
  template:
    metadata:
      labels:
        app: example3
    spec:
      containers:
        - name: example3
          image: nginx:latest
---
apiVersion: v1
kind: Service
metadata:
  name: example3
  namespace: alpha
spec:
  selector:
    app: example3
  ports:
    - port: 80
      targetPort: 80
