# Example 2
# Use kustomize from apps/bravo
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: example2-bravo
  namespace: bravo
spec:
  interval: 0m10s
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  path: ./apps/bravo/overlays/dev
  prune: true
  wait: true
  timeout: 5m0s
