# Example 1
# Yaml file directly in clusters/dev/namespaces/bravo
apiVersion: apps/v1
kind: Deployment
metadata:
  name: example1-bravo
  namespace: bravo
  labels:
    app: example1-bravo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: example1-bravo
  template:
    metadata:
      labels:
        app: example1-bravo
    spec:
      containers:
        - name: example1-bravo
          image: nginx:latest
---
apiVersion: v1
kind: Service
metadata:
  name: example1-bravo
  namespace: bravo
spec:
  selector:
    app: example1-bravo
  ports:
    - port: 80
      targetPort: 80
