# Example 1
# Yaml file directly in clusters/dev/namespaces/alpha
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mktp1
  namespace: echo
  labels:
    app: mktp1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mktp1
  template:
    metadata:
      labels:
        app: mktp1
    spec:
      containers:
        - name: mktp1
          image: nginx:latest
---
apiVersion: v1
kind: Service
metadata:
  name: mktp1
  namespace: echo
spec:
  selector:
    app: mktp1
  ports:
    - port: 80
      targetPort: 80
